src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PartnerTier__c</fullName>
        <label>Partner Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Strategic</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/PartnerTierConfiguration__mdt.object
<CustomObject>
    <description>This custom metadata type is used to setup Partner tier configuration</description>
    <label>Partner Tier Configuration</label>
    <pluralLabel>Partner Tier Configurations</pluralLabel>
</CustomObject>

src/classes/PostInstallPackageScript.cls
/*----------------------------------------------------------------------
Name: 		PostInstallPackageScript.cls
Purpose: 	Deploy/Perform Post Install Script of following Metadata using Apex Metadata API:
(1) Automatically add a new custom field "Partner Tier (PartnerTier__c)" on Account page layout "Demo Account Layout"
(2) Automatically create a default Managed package record in a custom metadata type "Partner Tier Configuration (PartnerTierConfiguration__mdt)"
------------------------------History----------------------------------
Version 	Author 		        Date 					Detail Description 
-------		--------------      -----------------       ------------------
1.0 		Muhammad Abrar 		10-May-2018	            Initial Development	
----------------------------------------------------------------------*/
public with sharing class PostInstallPackageScript implements InstallHandler{

	/*----------------------------------------------------------------------
    Purpose: 	Run Post Install Script to automatically:
    (1) Add a new custom field "Partner Tier (PartnerTier__c)" on Account page layout "Demo Account Layout"
    (2) Create a default Managed package record in a custom metadata type "Partner Tier Configuration (PartnerTierConfiguration__mdt)"
    Parameters: Metadata.DeployResult, Metadata.DeployCallbackContext
	Returns:	None
    ------------------------------History----------------------------------
    Version 	Author 		        Date 					Detail Description 
    -------		--------------      -----------------       ------------------
    1.0 		Muhammad Abrar 		10-May-2018	            Initial Development	
    ----------------------------------------------------------------------*/
    public void onInstall(InstallContext context) {
        // Run Post Package Installation Script
        DeployPackageMetadata deployPacakge = new DeployPackageMetadata();
        Metadata.DeployContainer container = deployPacakge.buildDeploymentContainer();
        deployPacakge.deploy(container);
    }
    
}